name: CI

on: [push, pull_request]

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
  rspec:
    name: RSpec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rspec spec
