name: Fully Jabbed - fetch and post

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get install jq
      - name: Fetch current vaccination uptake
        run: |
          FILE=./data/uptake.json
          url="https://coronavirus.data.gov.uk/api/v1/data?filters=areaName=United%2520Kingdom;areaType=overview&structure=%7B%22areaType%22:%22areaType%22,%22areaName%22:%22areaName%22,%22areaCode%22:%22areaCode%22,%22date%22:%22date%22,%22cumVaccinationFirstDoseUptakeByPublishDatePercentage%22:%22cumVaccinationFirstDoseUptakeByPublishDatePercentage%22,%22cumVaccinationSecondDoseUptakeByPublishDatePercentage%22:%22cumVaccinationSecondDoseUptakeByPublishDatePercentage%22%7D&format=json"
          response=$(curl -f "$url" --compressed)
          status=$?
          if [ $status -eq 0 ]; then
              echo $response > $FILE
              echo "$FILE saved."
          else
              echo "curl exit code: ($status) $response"
              exit $status
          fi
      - name: Get latest uptake percentage
        id: uptake
        run: echo ::set-output name=second::$(cat data/uptake.json | jq '.data[0] | .cumVaccinationSecondDoseUptakeByPublishDatePercentage')
      - name: Output uptake percentage
        run: echo ${{ steps.uptake.outputs.second }}
      - name: Tweet current uptake
        uses: devigned/go-twitter-action@v1
        with:
          message: ${{ steps.uptake.outputs.second }}
          apiKey: ${{ secrets.API_KEY }}
          apiKeySecret: ${{ secrets.API_KEY_SECRET }}
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          accessTokenSecret: ${{ secrets.ACCESS_TOKEN_SECRET }}
