name: World - fetch and post

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    env:
      DATA_URL: 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.json'
      TWITTER_SCREEN_NAME: 'fullyjabbed'
      JQ_FILTERS: '.[] | select(.iso_code == "OWID_WRL") | .data[-1] | .people_fully_vaccinated_per_hundred'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install jq
        run: sudo apt-get install jq
      - name: Fetch current vaccination uptake
        run: |
          FILE=./data/uptake.json
          response=$(curl -f "${{ env.DATA_URL }}" --compressed)
          status=$?
          if [ $status -eq 0 ]; then
              echo $response > $FILE
              echo "$FILE saved."
          else
              echo "curl exit code: ($status) $response"
              exit $status
          fi
      - name: Get latest uptake percentage
        id: uptake
        run: echo ::set-output name=fully::$(cat data/uptake.json | jq '${{ env.JQ_FILTERS }}' )
      - name: Format tweet
        id: tweet
        run: echo ::set-output name=formatted::$(bundle exec ruby lib/format_tweet.rb '${{ steps.uptake.outputs.fully }}')
      - name: Fetch last tweet
        id: last-tweet
        run: echo ::set-output name=text::$(bundle exec ruby lib/fetch_last_tweet.rb ${{ env.TWITTER_SCREEN_NAME }})
        env:
             API_KEY: ${{ secrets.API_KEY }}
             API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
             ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_WORLD }}
             ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET_WORLD }}
      - name: Debug output
        run: |
          echo ${{ steps.uptake.outputs.fully }}
          echo ${{ steps.tweet.outputs.formatted }}
          echo ${{ steps.last-tweet.outputs.text }}
      - name: Tweet current uptake
        if: steps.tweet.outputs.formatted != steps.last-tweet.outputs.text
        uses: devigned/go-twitter-action@v1
        with:
          message: ${{ steps.tweet.outputs.formatted }}
          apiKey: ${{ secrets.API_KEY }}
          apiKeySecret: ${{ secrets.API_KEY_SECRET }}
          accessToken: ${{ secrets.ACCESS_TOKEN_WORLD }}
          accessTokenSecret: ${{ secrets.ACCESS_TOKEN_SECRET_WORLD }}
